### ISSUE TITLE
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'endTime'; legal range is '^[0-9]{1,20}$'.

### ISSUE THREAD

**Issue by ehmirpro** [AbdulkareemAlmansoori/BinanceCryptoPricePredictor#1]
Hello 
i start this code :
crypto = client.get_historical_klines("ETHBTC", Client.KLINE_INTERVAL_30MINUTE, "1 Dec, 2017")
 but i got this error :
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 775, in get_historical_klines
    first_valid_ts = self._get_earliest_valid_timestamp(symbol, interval)
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 733, in _get_earliest_valid_timestamp
    endTime=None
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 715, in get_klines
    return self._get('klines', data=params)
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 217, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 186, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 181, in _request
    return self._handle_response(response)
  File "C:\Python\Python36\lib\site-packages\binance\client.py", line 210, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1100): Illegal characters found in parameter 'endTime'; legal range is '^[0-9]{1,20}$'.
`
but if i run this 
crypto=client.get_klines(symbol='ETHBTC', interval=Client.KLINE_INTERVAL_30MINUTE)
it works
what is the problem?

**Comment by ehmirpro** [comment]
for second code data is just about 500 candles,
i need more for training and test data...
please help
thanks .

**Comment by ehmirpro** [comment]
i found the problem ,
i downgrade python-binance to 0.7.1
